### PR TITLE
Putting db data on materials pages for design work

### PR DESCRIPTION
**Pull request by kstack7**
All of @Roenok's drafted elements are in place and waiting for CSS love :)

### CODE REVIEW

**Comment by juliaelman** [comment]
Looks good! :+1: A few notes + suggestions:

- It would be good to have a default image in case there is no image for that curriculum.
- Would it be possible to make those icons clickable to their curriculum detail page?

**Comment by kstack7** [comment]
@juliaelman totally possible...want me to add those before the merge?

**Comment by juliaelman** [comment]
@kstack7 yes please! Seems like it fits in with the issue enough not to have to separate it out into it's own thing. Thanks for asking!!!

**Comment by kstack7** [comment]
Sure...I kept it a VERY clean slate so that the designers could have fun. I can definitely get the links/ruby side in place for the cause :)

**Comment by Roenok** [comment]
Per my notes on the mockup, the default image is waiting for me to make. I'll be in a car all evening. Can I get that to you Saturday morning @kstack?

**Comment by kstack7** [comment]
@Roenok I'm totally fine with that. I was hoping for this sort of feedback as to what is needed as we go. We can wait to collect more at once :)

**Comment by kstack7** [comment]
K @juliaelman and @Roenok I added the icons to the page, adjusted the columns to 2-across, added new materials.css.scss for adjustments, swapped tags to match the new materials classes (mimicking states.css.scss setup), and linked up the icons for the pages. 

I stopped short in case others want to jump in. Let me know if you'd like more on there and I can keep going with it :)

**Comment by juliaelman** [comment]
@kstack7 looks good and thanks for adding in that default image :+1: 

@Roenok can you verify this looks good enough to merge in? If so, I am going to add an issue specifically for styling only.

**Comment by Roenok** [comment]
@juliaeleman Sadly, I still can't run the code in my dev environment. Can I
get screenshots or similar?

**Comment by juliaelman** [comment]
@Roenok see below. I'd like to add another issue for designing the materials detail page, as I'd like to just get this one merged in. Let me know what you think!

screen shot 2015-02-08 at 5 47 53 pm

screen shot 2015-02-08 at 5 48 03 pm

**Comment by Roenok** [comment]
Perfectly happy with that! Merge away, and I'll hit it with some CSS.

**Comment by kstack7** [comment]
:clap:

**Pull request merged**
