### PR TITLE
Adding missing states

### PR DESCRIPTION
**Pull request by Roenok**
Added png graphics for missing states per #160

### CODE REVIEW

**Comment by kstack7** [comment]
The pull request is nice and clean! :+1: buuut I'm going to be a bit nit-picky about the files themselves. I see a lot of aliasing on the edges of the states. I'm not sure if you can optimize your output settings or get that anti-aliasing rolling, but they're just a bit too jagged in comparison to the existing states. Also thinking we can up the detail on Rhode Island a bit, too. 

I'm going to hold off on this merge to hear from ya or others, k?

**Comment by kstack7** [comment]
Oh and for design purposes: do we want the states to appear straight as possible? I notice the existing ones often have vertical/horizontal edges instead of angles. Just hoping to establish consistency as we add more to the pile.

**Comment by Roenok** [comment]
Yeah, Rhode Island is problematic. The source map has it too small for details. I googled around, but did not find another (free) version.

**Comment by kstack7** [comment]
I had the same issues with my [super old] copies of CS. I thought it was the fact my stuff is outdated, but the source map IS pretty small. Can anyone chime in on smoothing out this process?

**Comment by Roenok** [comment]
Could we do them from a different source? I found a bunch of SVGs here http://libremap.org/data/boundary/

**Comment by Cara-Jo** [comment]
I just submitted a PR for this as well. I have a .ai file that I purchased ages ago that is all the state outlines in sexy vector format.

**Comment by Roenok** [comment]
You're awesome @cara-jo! Closing this PR, as it is superceeded by the new one.

**Pull request closed without merging**
