### PR TITLE
Issue #133 - Update to Rails 4.1.9

### PR DESCRIPTION
**Pull request by bayendor**
* Remove multiple references to same gem, e.g. unicorn

* Move gems into more logical groups, e.g dev, test

* Updated gems to current stable versions, e.g. pg, bourbon, bcrypt, event_machine, fog, etc.

* Remove rmagick gem, see issue #159, issue #130

* Ruby version bumped to 2.2.0 but not required.  Should we discuss? Heroku will complain if this is not set.

* All current tests passing.

### CODE REVIEW

**Comment by kstack7** [comment]
Upgraded to 4.1.9 and everything worked fine. Taking this to the next step by upgrading ruby to 2.2.0 to see how that goes. We could push this without the Ruby upgrade just to at least get Rails up to speed?

**Comment by bayendor** [comment]
@kstack7: Agreed.  In the meantime, several gems have been updated, included one moved from release candidate to formal release, including `eventmachine`, `mini_magick`, `rspec`, `guard`, etc..  Should I push those changes to this PR or wait?

**Comment by kstack7** [comment]
@bayendor I'm gonna say to add it so I can try it out...I'm not too sure about the ruby 2.2.0 push until it's more stable, but I don't think any of the gems will throw us for a loop. I'm happy we're pushing to better grounds before launch :)

**Comment by kstack7** [comment]
K moving to 4.1.9 is fine...not loving the ruby 2.2.0 push so let's hold back on that.

**Comment by kstack7** [comment]
Thanks for the quick responses @bayendor! Merging now...

**Pull request merged**
