### PR TITLE
add active state to nav on current page and reorder home so it is left m...

### PR DESCRIPTION
**Pull request by thejinxters**
This pull request adds an active state to the top navigation when we are at that current route.

It also reorders the li tags so that the "home" link is the first link.

### CODE REVIEW

**Comment by kstack7** [comment]
Just FYI, @thejinxters, the 'home' button may not stay in the nav. That is an open issue being discussed by our designers :)

**Comment by thejinxters** [comment]
Sounds good. should be easy to remove anyway :+1:

**Comment by Cara-Jo** [comment]
@kstack7 I think we could probably have them take care of that issue as well since I think the consensus is to remove it.

**Comment by kstack7** [comment]
I'm down if everyone else is.

**Comment by Cara-Jo** [comment]
:+1: Remove it! @thejinxters :house: :no_entry_sign:

**Comment by kstack7** [comment]
SMASH IT.

**Comment by thejinxters** [comment]
Home destroyed :no_good:

**Comment by Cara-Jo** [comment]
:100:

**Comment by juliaelman** [comment]
Refs #115

**Comment by kstack7** [comment]
This looks good on my end. :+1:

**Comment by juliaelman** [comment]
Awesome! Tests passing and merging in. Thx for your contribution @thejinxters :D

**Pull request merged**
