### PR TITLE
adding mailto links for /sponsors

### PR DESCRIPTION
**Pull request by minamarkham**

### CODE REVIEW

**Comment by minamarkham** [comment]
*crossing fingers*

**Comment by juliaelman** [comment]
@minamarkham this look good! I think what might be happening is that you are not branching from an updated master from the upstream branch. What is your workflow like when you create a new feature branch?

**Comment by minamarkham** [comment]
I think that's what happened. I forget to fetch the upstream when I start working on my changes. Then I couldn't figure out how to undo the changes, so I deleted that branch and started over.

**Comment by juliaelman** [comment]
@minamarkham aha! Got it. I am going to merge this in, but then fix up the commit history. Please make sure to run the following commands before branching off of master with your feature branch:

- `git fetch upstream`
- `git rebase upstream/master`

That will rebase all of the current changes on the main repos master onto your forked repo. Please feel free to reach out if you need help in the futures!

**Pull request merged**
