### PR TITLE
Seed data updates

### PR DESCRIPTION
**Pull request by therufs**
Pursuant to #287: 

Moved locs2.yml to sample-locs.yml
Annotated sample-locs.yml
Trimmed down seed locations
Updated docs (just a little bit)
Put sample-locs.yml in .gitignore (so you can always have your own chapter in your local db!) 

SF wasn't in the seeds to begin with, so I (somewhat arbitrarily) picked Chicago (they had a good variety of data.) 

Happy to incorporate suggestions :D :dancers:

### CODE REVIEW

**Comment by kstack7** [comment]
Hey @therufs...just noticing that the .gitignore updates have "seed-locs.yml" and not "sample-locs.yml" like the code. Can you adjust this and commit once more? Everything else looks good :) Thanks!

**Comment by therufs** [comment]
Loooool, good catch. Fixed now! :stuck_out_tongue_winking_eye:

**Comment by kstack7** [comment]
@therufs easy one, right? :) Thanks, lady!

**Comment by therufs** [comment]
\o/

**Pull request merged**
