### PR TITLE
resolving #238 where footer doesn't reach bottom of page on mobile

### PR DESCRIPTION
**Pull request by joshuamauldin**
Hope that helps!

### CODE REVIEW

**Comment by joshuamauldin** [comment]
I changed the footer element to have a min-height, preserving any logic that made the height fixed in the first place.

**Comment by kstack7** [comment]
hey @joshuamauldin! Thanks for the PR. Would you mind adding a slight adjustment? The min-height does help, but I think we need to pad the bottom of the footer to make sure the social media icons stay off the very bottom. Can you update the "padding: 20px 0px 0px 0px;" to "padding: 20px 0;" alongside your min-height change? This seems to make things happier for small screens.

Thank you again!

**Comment by kstack7** [comment]
Hey @joshuamauldin is that something you can easily add? Let me know if not and I'll push your PR before adding my change on top. Thanks!

**Comment by joshuamauldin** [comment]
I did add that, should I have made a comment here about that, too? (this was my first pull request!)

**Comment by kstack7** [comment]
Woo! Hooray for first pull requests! Going to merge this now. Thanks so much for your help, @joshuamauldin! We appreciate it!

**Pull request merged**
