### PR TITLE
Update .gitignore file to include .DS_Store and Travis CI files.

### PR DESCRIPTION
**Pull request by juliaelman**

### CODE REVIEW

**Comment by kstack7** [comment]
My ONLY hangup is that I don't think the wildcard is necessary for the .DS_Store here...may be a tad nit-picky but throwing that down for thoughts!

**Comment by juliaelman** [comment]
@kstack7 my vote is to keep it as a wildcard to help avoid any stray little buggers inside sub-directories, etc. More of a fail safe to help avoid any issues of it appearing in another PR.

**Comment by kstack7** [comment]
Have you ever seen the  **/.DS_Store approach for subdirectory catches? I've been seeing a couple approaches so I'm double-checking with git's docs: "A leading "**" followed by a slash means match in all directories."

**Comment by kstack7** [comment]
WOAH. git does NOT like double asterisks haha

**Comment by juliaelman** [comment]
@kstack7 I think it would be best to leave the "/" out of the way of the .DS_Store file to help avoid any confusion as to whether or not that file itself is a directory. The "*" helps avoid any stray files that might have hidden spaces in front of them or other things that might make them tricky to catch.

Looking forward to reading what you think and how best to move forward! :tada:

**Comment by kstack7** [comment]
I'm down for taking your experience over the stuff I was reading today...I'm not sure I like the two lines I suggested anyways so let's go with your commits and we can always swap out if things go awry (super unlikely). Wanna do zee honors?

**Comment by juliaelman** [comment]
Awesome, thanks @kstack7! <3

**Pull request merged**
