### PR TITLE
Fixes #203 chapter/bio page dropdown bug in Active Admin

### LINKED ISSUE #203: Chapter names and Admin names are not parsing correctly in the admin.
**Description** 
When navigating to the bios section of the admin page, the names are displayed wrong. They should be displayed with human readable names like "Boulder, Philadelphia" for the chapter names or "Cara Jo, Kristen" for the admin names.

 **Ask** 
Please fix this so we can sort through all the bios! Many people! 

 **To Do** 
 - [ ] Fix Admin name display
 - [ ] Fix Chapter Name Display 
 - [ ] Celebrate

 **Additional Info** 
Here's a screenshot of the culprit.
screenshot 2015-02-11 10 52 57

### PR DESCRIPTION
**Pull request by kstack7**
Dropdowns are much prettier now :)

### CODE REVIEW

**Comment by DBNess** [comment]
Screenshot pls? Thx <3

**Comment by kstack7** [comment]
Sure!

Both dropdowns on bio/sponsors: 

screen shot 2015-02-14 at 12 46 30 am
screen shot 2015-02-14 at 12 46 11 am

**Comment by kstack7** [comment]
I didn't quite nail the "admin user" dropdown since I think that has to do with database relationships, but you can still do a filter on the name if needed :)

Here's a filter result with my name for example:

screen shot 2015-02-14 at 12 49 21 am

**Comment by juliaelman** [comment]
Beautimus!

**Pull request merged**
