### PR TITLE
Homepage animations without animate.css library

### PR DESCRIPTION
**Pull request by amygori**
This completely removes the animate.css library and restores only the css for the fade-in left/right on the header. I'd be glad to know if the animation durations and delays are to everyone's liking.

### CODE REVIEW

**Comment by kstack7** [comment]
Hey @amygori! Thanks for cleaning up this animate fun :) I really like having it condensed like this. Could I suggest that you change the animation-duration to 1.2s and add easing to both .fadeInLeft and .fadeInRight:

-webkit-animation-timing-function: ease-out;
  animation-timing-function: ease-out;

That'll make it look pretty consistent to the rate of the live site :)

**Comment by amygori** [comment]
will do, @kstack7. thanks for the feedback!

**Comment by amygori** [comment]
I think you're right. Let me change that.

**Comment by kstack7** [comment]
I like it! The right animation is a bit behind the live version now, but I don't mind that since it lets you fully read the first line before the next comes in. I'm going to merge. Thanks for the optimization! :+1:

**Pull request merged**
