### PR TITLE
Updates Rails version to 4.1.9

### PR DESCRIPTION
**Pull request by coreyd303**

### CODE REVIEW

**Comment by juliaelman** [comment]
@coreyd303 looks like the .gitignore change is also in this one and needs to be updated/removed in order to merge nicely :)

**Comment by bayendor** [comment]
FYI, I've been experimenting on running this on Rails 4.2.0 and Ruby 2.2.0.  Nothing we are doing is particularly dependent on anything in Rails earlier than 2.0.  So far I've found no issues.  I've also been working on cleaning the Gemfile as part of this, since we have some duplication / redundant gems.  I'll probably do a test deploy on my own VPS just to see how it behaves in production and open an issue when I have more to discuss.  Initially, all parts of the site are running with on the most current Ruby, Rails, and a few other updated gems.  We can probably discuss as we get closer to production rollout.

**Comment by juliaelman** [comment]
Thanks for your feedback @bayendor! \o/ I'll be on the lookout for your PR with the Gemfile update. Appreciate your work on this project :+1:

**Comment by juliaelman** [comment]
Closing this, as #172 accomplishes the same thing.

**Pull request closed without merging**
