### PR TITLE
create sponsors page

### PR DESCRIPTION
**Pull request by minamarkham**

### CODE REVIEW

**Comment by juliaelman** [comment]
@minamarkham looks like there is a merge conflict in the following files:

- app/views/shared/_header.html.erb
- config/routes.rb

It looks like it is a matter of rebasing the current state of master with your changes. When you get a chance, would you mind making that fix and pushing it up? Happy to help if you need it! \o/

**Comment by minamarkham** [comment]
@juliaelman I think I fixed the problem. Let me know if that works.

**Comment by juliaelman** [comment]
@minamarkham hrmmm... still looks like those files are having merge conflicts, but they are different than before.

**Comment by minamarkham** [comment]
yeah, I suck as git.
stand by.

**Comment by minamarkham** [comment]
@juliaelman Okay. I think I really fixed it.

**Comment by corinnepw** [comment]
I apologize for the delay @minamarkham & @juliaelman and all!

To include for launch:
----
**Sponsors**

Esri 
esri-logo-1

Mandrill 
mandrill_shield-0b07ab92

Knight Foundation
knight-logo-3000

Craigslist
craigslist_01

**Partners**
Code for America
cfa_logo_lg-1

AOL 
2000px-aol_logo svg-2

Black Girls Code (logo already uploaded)

That should be all for launch. Can add more soon!

**Comment by minamarkham** [comment]
@corinnepw @juliaelman what do we think?

logos

**Comment by juliaelman** [comment]
:heart: :heart: :heart:  you are awesome!

**Comment by corinnepw** [comment]
Super love <3 @minamarkham

**Comment by minamarkham** [comment]
Pushed new commit! :smiley:

**Pull request merged**
