### PR TITLE
Rolling back ruby to 2.0.0 to help with memory leaks, fixes #257

### LINKED ISSUE #257: Memory leaks with Ruby 2.1.2
**Description**
*We have been noticing a number of "memory leak/exceeded memory limit" warnings in our logs this week. Only pattern so far is that it seems to occur around 4PM and more often around the chapter pages.*

**Ask**
*Find if the memory leaks are due to our code of if we should roll back to Ruby 2.0.0 (see links below)*

**To Do**
- [ ] Research exceeded memory errors on Heroku
- [ ] Analyze gemfile and look for potential memory hogs
- [ ] Implement the solution that will reduce memory usage

**Additional Info**
Useful threads: 
- https://discussion.heroku.com/t/memory-leaks-with-ruby-2-1-2/644/3
- http://blog.skylight.io/hunting-for-leaks-in-ruby/

### PR DESCRIPTION
**Pull request by kstack7**
Putting this here if we agree to try the rollback fix I suggested :)

### CODE REVIEW

**Comment by kstack7** [comment]
Ruby 2.0.0 ready to go if we'd like :)

**Comment by kstack7** [comment]
@DBNess does this look smooth to you? I was thinking we could try it out once the feature traction has eased up.

**Comment by DBNess** [comment]
@kstack7 looks nice & clean! thank you! Holding off on actually merging this since our memory usage looks consistent / not much like a leak now, as we discussed, but glad we have this ready to go :+1: :ok_hand:

**Comment by kstack7** [comment]
Thanks @DBNess...sounds good!

**Comment by kstack7** [comment]
Closing for now to clean up the PR list. We can always reopen if needed, but unlikely.

**Pull request closed without merging**
